export const languageOptions = [
    { code: 'en-US', name: 'English (United States)' },
    { code: 'de-DE', name: 'German (Germany)' },
    { code: 'es-ES', name: 'Spanish (Spain)' },
    { code: 'fr-FR', name: 'French (France)' },
    { code: 'ru-RU', name: 'Russian (Russia)' },
    { code: 'uk-UA', name: 'Ukrainian (Ukraine)' },
    { code: 'pl-PL', name: 'Polish (Poland)' },
    { code: 'it-IT', name: 'Italian (Italy)' },
    { code: 'pt-PT', name: 'Portuguese (Portugal)' },
    { code: 'ja-JP', name: 'Japanese (Japan)' },
    { code: 'zh-CN', name: 'Chinese Simplified (China)' },
    { code: 'zh-TW', name: 'Chinese Traditional (Taiwan)' },
    { code: 'ko-KR', name: 'Korean (South Korea)' },
    { code: 'ar-SA', name: 'Arabic (Saudi Arabia)' },
    { code: 'hi-IN', name: 'Hindi (India)' },
    { code: 'bn-BD', name: 'Bengali (Bangladesh)' },
    { code: 'nl-NL', name: 'Dutch (Netherlands)' },
    { code: 'sv-SE', name: 'Swedish (Sweden)' },
    { code: 'no-NO', name: 'Norwegian (Norway)' },
    { code: 'fi-FI', name: 'Finnish (Finland)' },
    { code: 'da-DK', name: 'Danish (Denmark)' },
    { code: 'tr-TR', name: 'Turkish (Turkey)' },
    { code: 'cs-CZ', name: 'Czech (Czech Republic)' },
    { code: 'el-GR', name: 'Greek (Greece)' },
    { code: 'he-IL', name: 'Hebrew (Israel)' },
    { code: 'th-TH', name: 'Thai (Thailand)' },
    { code: 'vi-VN', name: 'Vietnamese (Vietnam)' },
    { code: 'id-ID', name: 'Indonesian (Indonesia)' },
    { code: 'ms-MY', name: 'Malay (Malaysia)' },
    { code: 'fil-PH', name: 'Filipino (Philippines)' },
    { code: 'hu-HU', name: 'Hungarian (Hungary)' },
    { code: 'ro-RO', name: 'Romanian (Romania)' },
    { code: 'sk-SK', name: 'Slovak (Slovakia)' },
    { code: 'sl-SI', name: 'Slovenian (Slovenia)' },
    { code: 'hr-HR', name: 'Croatian (Croatia)' },
    { code: 'bg-BG', name: 'Bulgarian (Bulgaria)' },
    { code: 'sr-RS', name: 'Serbian (Serbia)' },
    { code: 'lt-LT', name: 'Lithuanian (Lithuania)' },
    { code: 'lv-LV', name: 'Latvian (Latvia)' },
    { code: 'et-EE', name: 'Estonian (Estonia)' },
    { code: 'ca-ES', name: 'Catalan (Spain)' },
    { code: 'ga-IE', name: 'Irish (Ireland)' },
    { code: 'mt-MT', name: 'Maltese (Malta)' },
    { code: 'is-IS', name: 'Icelandic (Iceland)' },
    { code: 'mk-MK', name: 'Macedonian (North Macedonia)' },
    { code: 'sq-AL', name: 'Albanian (Albania)' },
    { code: 'bn-IN', name: 'Bengali (India)' },
    //...
];